Target  = libkcp.a
Include =
Source	= ikcp.c
LibDir	=
Lib 	=
ObjDir	= ../../obj
OutDir	= ../../lib
Define 	=
CFLAGS	=
CXXFLAGS =
LDFLAGS =
AfterBuild = mkdir -p ../../include/kcp & cp ikcp.h ../../include/kcp

include ../../utils/makefile
