Target  = libkcp.a
Include =
Source	= ikcp.c
LibDir	=
Lib 	=
ObjDir	= ../../obj
OutDir	= ../../lib
Define 	=
CFLAGS	=
CXXFLAGS =
LDFLAGS =
AfterBuild = cp ikcp.h ../../include/kcp

$(shell mkdir -p ../../include/kcp)

include ../../utils/makefile
