Target  = luxd
Include = ../include/lua ../include/stm
Source	= main.cpp
LibDir	= ../lib
Lib 	= lux
ObjDir	= ../obj
OutDir	= ../bin
Define 	=
CFLAGS	=
CXXFLAGS =
LDFLAGS =
Rpath = ../lib

include ../utils/makefile
